#!/usr/bin/env python3
"""Generate the driver artefacts (design 10.1, 1.4 R4): embed the stop signatures into
drivers/detect_page.js and write drivers/manifest.json = {driver name: sha256 of its exact function text}.

    python3 tools/gen_drivers.py            # regenerate in place
    python3 tools/gen_drivers.py --check    # exit 1 when a file is out of date (CI)

Signatures: every stop signature of scripts/jobhunter/detect/{linkedin,gmail,ats,boards}.json (U1) that has a
url, title or text regex, in file order, followed by the research baseline below (linkedin-limits.md section
4, design 4.5), the patterns common to every family and the structural probes. Each embedded signature keeps
its id, reason_code, trip and job_needs_human, so the page picks the most severe hit the way `jh.py detect`
does (jobhunter.detect._rank): a tripping stop before a job-level stop, then the reason's place in
jobhunter.detect.SEVERITY (embedded too, so there is one source), then the order above. HTTP-status
signatures are not embedded (a page script cannot see the status); `jh.py detect` and the guard still match
them. Only patterns that compile in Python and use no Python-only syntax are embedded, so the page can run
them with `new RegExp(p, 'i')`.

Function text and hash: the driver file content with surrounding whitespace removed (str.strip()), UTF-8;
the agent passes exactly that text to the browser `evaluate` action and the guard compares its sha256 with
the manifest after the same strip.
"""
from __future__ import annotations

import argparse
import glob
import hashlib
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRIVERS_DIR = os.path.join(REPO, "drivers")
DETECT_DIR = os.path.join(REPO, "scripts", "jobhunter", "detect")
DETECT_DRIVER = "detect_page.js"
BEGIN = "  /* BEGIN SIGNATURES (generated by tools/gen_drivers.py; do not edit by hand) */"
END = "  /* END SIGNATURES */"
FAMILIES = ("linkedin", "gmail", "ats", "boards")
WHERE = ("url", "title", "text")

# Copy of jobhunter.detect.SEVERITY, used only when that module cannot be imported (a test keeps them equal).
SEVERITY_FALLBACK = (
    "li_restricted", "li_identity_mismatch", "li_challenge", "li_security_email", "li_logged_out",
    "li_invite_limit", "li_easy_apply_limit", "li_messaging_blocked", "li_email_needed",
    "li_commercial_limit", "li_http_429", "li_unknown_modal",
    "gmail_security", "gmail_auth_failed", "gmail_identity_mismatch", "gmail_logged_out", "gmail_sending_limit",
    "gmail_unexpected_state", "ats_security", "ats_blocked", "site_challenge", "site_logged_out")

# Research baseline: (where, pattern, reason). Every baseline stop trips its reason's breaker, except the
# JOB_LEVEL reasons: on an ATS company form a CAPTCHA or an account wall stops only that job.
BASELINE = {
    "linkedin": [
        ("url", r"/checkpoint/", "li_challenge"), ("url", r"/challenge", "li_challenge"),
        ("url", r"/authwall", "li_challenge"), ("url", r"linkedin\.com/verify", "li_challenge"),
        ("url", r"/uas/login", "li_logged_out"), ("url", r"linkedin\.com/login", "li_logged_out"),
        ("url", r"/signup", "li_logged_out"),
        ("text", r"unusual activity", "li_restricted"), ("text", r"temporarily restricted", "li_restricted"),
        ("text", r"account has been restricted", "li_restricted"),
        ("text", r"restricted your account", "li_restricted"), ("text", r"verify your identity", "li_restricted"),
        ("text", r"confirm your identity", "li_restricted"), ("text", r"government.issued ID", "li_restricted"),
        ("text", r"sign.in security prompt", "li_challenge"), ("text", r"security verification", "li_challenge"),
        ("text", r"security check", "li_challenge"), ("text", r"try a different image", "li_challenge"),
        ("text", r"let.s do a quick security check", "li_challenge"),
        ("text", r"weekly invitation limit", "li_invite_limit"), ("text", r"invitation limit", "li_invite_limit"),
        ("text", r"you.re out of", "li_invite_limit"),
        ("text", r"reached today.s easy apply limit", "li_easy_apply_limit"),
        ("text", r"easy apply.{0,40}temporary pause", "li_easy_apply_limit"),
        ("text", r"email address needed", "li_email_needed"), ("text", r"enter their email", "li_email_needed"),
        ("text", r"commercial use limit", "li_commercial_limit"), ("text", r"monthly limit", "li_commercial_limit"),
        ("text", r"too many requests", "li_http_429"), ("text", r"sending too many", "li_http_429"),
    ],
    "gmail": [
        ("url", r"accounts\.google\.com/(v3/)?signin", "gmail_security"),
        ("url", r"accounts\.google\.com/ServiceLogin", "gmail_security"),
        ("url", r"accounts\.google\.com/.*challenge", "gmail_security"), ("url", r"/sorry/", "gmail_security"),
        ("text", r"unusual activity", "gmail_security"), ("text", r"verify it.s you", "gmail_security"),
        ("text", r"account (has been )?disabled", "gmail_security"),
        ("text", r"account (has been )?suspended", "gmail_security"),
        ("text", r"confirm your recovery", "gmail_security"), ("text", r"too many requests", "gmail_security"),
        ("text", r"you have reached a limit for sending mail", "gmail_sending_limit"),
    ],
    "ats": [
        ("text", r"verify you are (a )?human", "captcha_visible"),
        ("text", r"complete the security check", "captcha_visible"),
        ("text", r"create (an )?account to apply", "account_required"),
        ("text", r"sign (in|up) to apply", "account_required"),
    ],
    "boards": [
        ("url", r"/login", "site_challenge"), ("url", r"/signin", "site_challenge"),
        ("url", r"/nlogin", "site_challenge"), ("url", r"/captcha", "site_challenge"),
        ("text", r"unusual activity", "site_challenge"), ("text", r"verify you are (a )?human", "site_challenge"),
        ("text", r"daily limit", "site_challenge"), ("text", r"limit reached", "site_challenge"),
        ("text", r"you have reached (the|your) (daily|weekly|monthly) limit", "site_challenge"),
        ("text", r"too many requests", "site_challenge"), ("text", r"login to continue", "site_challenge"),
        ("text", r"please log ?in to apply", "site_challenge"), ("text", r"session (has )?expired", "site_challenge"),
    ],
}
JOB_LEVEL = ("captcha_visible", "account_required")

# Patterns every family checks: (where, pattern, kind), kind "challenge" or "block".
COMMON = [("url", r"captcha", "challenge"), ("text", r"\bcaptcha\b", "challenge"),
          ("text", r"i.m not a robot", "challenge"), ("text", r"are you a robot", "challenge"),
          ("text", r"access denied", "block"), ("text", r"429 too many requests", "block"),
          ("text", r"\berror 999\b", "block")]
# What a common hit means per family: a reason_code, or a job-level reason on ATS forms.
COMMON_REASON = {
    "linkedin": {"challenge": "li_challenge", "block": "li_http_429"},
    "gmail": {"challenge": "gmail_security", "block": "gmail_security"},
    "ats": {"challenge": "captcha_visible", "block": "ats_blocked"},
    "boards": {"challenge": "site_challenge", "block": "site_challenge"},
}
# Structural checks the page runs itself (no regex): a CAPTCHA frame, a visible password field (signed out
# of a platform or a board) and an ATS account wall (a password field or account wording on a company form).
PROBES = {
    "linkedin": [("captcha_frame", "li_challenge"), ("login_form", "li_logged_out")],
    "gmail": [("captcha_frame", "gmail_security"), ("login_form", "gmail_security")],
    "ats": [("captcha_frame", "captcha_visible"), ("account_wall", "account_required")],
    "boards": [("captcha_frame", "site_challenge"), ("login_form", "site_challenge")],
}

_PY_ONLY = re.compile(r"\(\?P|\(\?[aiLmsux]+[):]|\(\?<[=!]|\\A|\\Z|\(\?#")
_ID_RE = re.compile(r"^[a-z0-9_]{1,60}$")


def severity() -> tuple:
    """jobhunter.detect.SEVERITY (U1), so the page ranks reasons exactly as `jh.py detect` does."""
    scripts = os.path.join(REPO, "scripts")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    try:
        from jobhunter import detect
        return tuple(detect.SEVERITY)
    except Exception:   # the generator still works when U1's module is broken or absent
        return SEVERITY_FALLBACK


def _valid(p) -> bool:
    if not isinstance(p, str) or not p or len(p) > 300:
        return False
    try:
        p.encode("ascii")
        re.compile(p)
    except (UnicodeEncodeError, re.error):
        return False
    return not _PY_ONLY.search(p)


def _sig(sid: str, reason: str, where: str, pattern: str) -> dict:
    """One embedded signature; a JOB_LEVEL reason is a job-level stop (trip false, job_needs_human)."""
    if reason in JOB_LEVEL:
        return {"id": sid, "reason_code": None, "trip": False, "job_needs_human": reason, where: pattern}
    return {"id": sid, "reason_code": reason, "trip": True, "job_needs_human": None, where: pattern}


def _from_file(data: dict, fam: str) -> list:
    """Stop signatures of one detect/*.json file with a url, title or text regex, in file order."""
    out = []
    for i, s in enumerate(data.get("signatures") or []):
        if not isinstance(s, dict) or s.get("verdict", "stop") != "stop":
            continue
        sid = s["id"] if isinstance(s.get("id"), str) and _ID_RE.match(s["id"]) else "%s_file_%d" % (fam, i + 1)
        rc = s.get("reason_code") if isinstance(s.get("reason_code"), str) else None
        jnh = s.get("job_needs_human") if isinstance(s.get("job_needs_human"), str) else None
        for where in WHERE:
            if _valid(s.get(where)):
                out.append({"id": sid, "reason_code": rc, "trip": bool(s.get("trip")), "job_needs_human": jnh,
                            where: s[where]})
    return out


def signatures(detect_dir: str = DETECT_DIR) -> dict:
    """{family: [signature, ...]}: detect file signatures, then the baseline, then the common patterns (a
    (where, pattern) pair already embedded for the family is not repeated), then the probes."""
    sig = {}
    for fam in FAMILIES:
        items = []
        try:
            with open(os.path.join(detect_dir, fam + ".json"), "r", encoding="utf-8") as fh:
                items += _from_file(json.load(fh), fam)
        except (OSError, ValueError, AttributeError):
            pass
        for n, (where, pat, reason) in enumerate(BASELINE[fam], 1):
            items.append(_sig("baseline_%s_%d" % (fam, n), reason, where, pat))
        for n, (where, pat, kind) in enumerate(COMMON, 1):
            items.append(_sig("common_%s_%d" % (fam, n), COMMON_REASON[fam][kind], where, pat))
        seen, uniq = set(), []
        for s in items:
            where = next(w for w in WHERE if w in s)
            if not _valid(s[where]) or (where, s[where]) in seen:
                continue
            seen.add((where, s[where]))
            uniq.append(s)
        uniq += [_sig("probe_" + probe, reason, "probe", probe) for probe, reason in PROBES[fam]]
        sig[fam] = uniq
    return sig


def rank(sig: dict, order: int, sev=None) -> tuple:
    """Sort key of a matching signature (smaller wins), the same as jobhunter.detect._rank and the page."""
    sev = list(sev if sev is not None else severity())
    rc = sig.get("reason_code") or ""
    return (0 if sig.get("trip") else 1, sev.index(rc) if rc in sev else len(sev), order)


def render_block(sig: dict, sev=None) -> str:
    sev = list(sev if sev is not None else severity())
    lines = [BEGIN, "  const SEVERITY = %s;" % json.dumps(sev, ensure_ascii=True), "  const SIG = {"]
    fams = [f for f in FAMILIES if f in sig]
    for i, fam in enumerate(fams):
        body = json.dumps(sig[fam], ensure_ascii=True, sort_keys=True)
        lines.append("    %s: %s%s" % (fam, body, "," if i < len(fams) - 1 else ""))
    lines += ["  };", END]
    return "\n".join(lines)


def parse_block(text: str) -> tuple:
    """(SEVERITY, SIG) read back from a detect_page.js text (tests)."""
    block = text[text.index(BEGIN):text.index(END)]
    m = re.search(r"const SEVERITY = (\[.*?\]);", block)
    sev = json.loads(m.group(1)) if m else []
    sig = {fam: json.loads(body) for fam, body in re.findall(r"^ {4}(\w+): (\[.*\]),?$", block, flags=re.M)}
    return sev, sig


def embed(text: str, sig: dict, sev=None) -> str:
    start = text.index(BEGIN)
    stop = text.index(END, start) + len(END)
    return text[:start] + render_block(sig, sev) + text[stop:]


def function_text(content: str) -> str:
    return content.strip()


def sha256_function(content: str) -> str:
    return hashlib.sha256(function_text(content).encode("utf-8")).hexdigest()


def build(drivers_dir: str = DRIVERS_DIR, detect_dir: str = DETECT_DIR) -> dict:
    """{path: new content} for detect_page.js and manifest.json."""
    out = {}
    det = os.path.join(drivers_dir, DETECT_DRIVER)
    with open(det, "r", encoding="utf-8") as fh:
        out[det] = function_text(embed(fh.read(), signatures(detect_dir))) + "\n"
    manifest = {}
    for path in sorted(glob.glob(os.path.join(drivers_dir, "*.js"))):
        if path in out:
            content = out[path]
        else:
            with open(path, "r", encoding="utf-8") as fh:
                content = fh.read()
        manifest[os.path.splitext(os.path.basename(path))[0]] = sha256_function(content)
    out[os.path.join(drivers_dir, "manifest.json")] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail when a generated file is out of date")
    args = ap.parse_args(argv)
    stale = []
    for path, content in build().items():
        try:
            with open(path, "r", encoding="utf-8") as fh:
                current = fh.read()
        except OSError:
            current = None
        if current != content:
            stale.append(os.path.relpath(path, REPO))
            if not args.check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(content)
    if args.check and stale:
        print("out of date: %s (run python3 tools/gen_drivers.py)" % ", ".join(stale))
        return 1
    print("updated: %s" % (", ".join(stale) if stale else "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
